version: '3.7'

services:
  react-app:
    image: nginx:latest
    container_name: app_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf