name: Deploy to Production

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        USER: ${{ secrets.USER }}
        HOST: ${{ secrets.HOST }}
      run: |
        echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
        echo "USER: $USER"
        echo "HOST: $HOST"
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $HOST >> ~/.ssh/known_hosts

    - name: Try to connect to SSH and run commands
      env:
        USER: ${{ secrets.USER }}
        HOST: ${{ secrets.HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
          echo "Connected to $HOST"
          cd /home/containers/React_App_Learning_01
          yarn install
          yarn run build
        EOF

