name: Deploy to Production

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        if [ -z "$SERVER_HOST" ]; then
          echo "SERVER_HOST is not set"
          exit 1
        fi
        ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
        echo "SSH setup completed"
        ls -la ~/.ssh
        cat ~/.ssh/known_hosts

    - name: Test SSH connection and check versions
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
          echo "SSH connection successful"
          git --version
          node --version
        EOF

    - name: Deploy to server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /path/to/your/project
          git pull origin master
          npm install
          npm run build
          pm2 restart all
        EOF